---
exclude:
- Gemfile
- Gemfile.lock
- lib
title: Samuchai
baseurl: /
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  bundles:
    - 'application.css'
    - 'application.js'
  compress:
    css: sass
    js: uglifier
  cachebust: hard
  gzip:
  - text/css
  - application/javascript
env: staging